### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by xtechgamer735** [innovate-technologies/whmcs-gocardless#1]
Hello!

Wonderful add-on - thanks so much!

I just wondered if Subscriptions would work as such if powered by WHMCS? Is it possible for it to automatically capture payment as long as the mandate is setup for example on a monthly recurring product?

Many thanks

**Comment by meyskens** [comment]
We wanted this feature but WHMCS didn’t offer a good API for that. It does have automatic payments using the credit card capture capabilities

**Comment by xtechgamer735** [comment]
I do like the credit cards but a lot of my clients are businesses you see and dont have access to credit or debit cards. While it seems strange im not suprised about the WHMCS api really, I dont like the system if im honest but its about the best out there haha

**Comment by meyskens** [comment]
I meant that we use the API designed for that to do automatic direct debit.

**Comment by xtechgamer735** [comment]
Ah I see, so does the add-on do the automatic direct debits?

**Comment by meyskens** [comment]
Yup (sorry for the delay)

**Comment by xtechgamer735** [comment]
Ah okay that’s helpful thank you
